异常处理
1. throw 抛出异常
2. try尝试执行
3.catch捕获异常

throw可以抛出特定类型的异常，try捕获异常后函数退出，catch捕获判断类型然后处理异常

---------------------------------------------------------------------------------------------------------------------------------
int abc(int a, int b, int c)
{
	if (a < 0 && b < 0 && c < 0)
	{
		throw 1;
	}
	else if (a == 0 && b == 0 && c == 0)
	{
		throw 2;
	}
	return  a + b * c;
}

int main()
{
	try { abc(0, 0, 0); }
	catch (char *e)
	{
		std::cout << "catch exception is" << e << std::endl;
	}
	catch (int e)
	{
		std::cout << "catch exception is" << e << std::endl;
	}
	catch (...)
	{
		std::cout << "catch some exception" << std::endl;
	}
}

---------------------------------------------------------------------------------------------------------------------------------




